# Docker Compose file for Cytoscape App Store

appstore:
  build: .
  ports:
    - "80:80"
  links:
    - mysql

mysql:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: 
    MYSQL_DATABASE: 
    MYSQL_USER: 
    MYSQL_PASSWORD: 