# Docker Compose file for Cytoscape App Store


db:
  image: mysql

appstore:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db